title: payload-vars
description: Validate JSON templates, extract typed variables, and render payloads.
url: https://thismeansmore.github.io
baseurl: /payload-vars
theme: minima
github_username: ThisMeansMore

header_pages:
  - examples.md
  - syntax.md
  - plugins.md
  - development.md
  - changelog.md

plugins:
  - jekyll-relative-links

defaults:
  - scope:
      path: ""
    values:
      layout: default
